import type {
  DepartmentArchiveRecord,
  DepartmentId,
  MediaAsset,
} from './types'

const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`.replace(/\/+/g, '/')

const hero = (
  id: DepartmentId,
  alt: string,
  objectPosition: string,
): MediaAsset => ({
  src: asset(`departments/${id}/hero-1200.webp`),
  srcSet: `${asset(`departments/${id}/hero-600.webp`)} 600w, ${asset(`departments/${id}/hero-1200.webp`)} 1200w`,
  alt,
  objectPosition,
})

const gallery = (
  id: DepartmentId,
  alts: [string, string, string],
  positions: [string, string, string] = ['50% 50%', '50% 50%', '50% 50%'],
): MediaAsset[] =>
  alts.map((alt, index) => ({
    src: asset(`departments/${id}/gallery-${index + 1}-640.webp`),
    alt,
    objectPosition: positions[index],
  }))

export const departmentArchives: DepartmentArchiveRecord[] = [
  {
    id: 'office',
    name: '办公室',
    summary: '把财务、物资、档案和协作节点稳稳接住，让中心的每项工作有序落地。',
    mission: '在细节中守住秩序，在协作中推动全局。',
    accent: '#4fc3a1',
    hero: hero('office', '办公室成员与中心同学在培训活动后合影', '50% 46%'),
    gallery: gallery('office', [
      '办公室成员在室外活动点位承担咨询与现场保障',
      '办公室参与大型活动并完成现场合影记录',
      '办公室与其他部门成员在活动结束后合影',
    ]),
    responsibilities: [
      '审核报销材料，整理财务、物资和档案信息',
      '对接学院与中心各部门，提醒任务节点并汇总进度',
      '服务双选会、赛事、讲座等活动，做好人员与现场保障',
      '通过实操培训帮助成员掌握规范、高效的事务处理方法',
    ],
    stats: [
      { value: 33, suffix: '项', label: '报销材料审核', note: '按规范完成材料核对与整理' },
      { value: 3, suffix: '期', label: '财务实操培训', note: '让成员在真实任务中熟悉流程' },
      { value: 10, suffix: '+场', label: '活动统筹支持', note: '覆盖双选会、赛事与讲座等场景' },
    ],
    workflow: [
      { title: '接收任务', description: '确认材料、物资、人员和时间节点，明确责任人。' },
      { title: '核对清单', description: '逐项检查信息完整性，把问题在执行前处理清楚。' },
      { title: '协同推进', description: '联系学院与各部门，跟进节点并及时补位。' },
      { title: '归档复盘', description: '整理票据、文件和活动记录，为后续工作留下依据。' },
    ],
    gains: ['财务与行政事务处理能力', '跨部门沟通和节点管理经验', '大型活动现场统筹能力'],
    starterAction: '跟着一次活动，把物资和人员清单核对一遍。',
    related: ['project', 'competition'],
  },
  {
    id: 'project',
    name: '项目部',
    summary: '陪伴一个科创想法从选题、立项、跟进走向结题和更高层级的赛事舞台。',
    mission: '让项目有人跟、问题有人解、成长看得见。',
    accent: '#4aa8ff',
    hero: hero('project', '项目部成员在创新创业活动现场合影', '50% 45%'),
    gallery: gallery(
      'project',
      [
        '项目部成员参加创新创业交流活动并合影',
        '项目部与交流团队完成活动记录',
        '项目部使用线上清单持续跟进项目问题',
      ],
      ['50% 50%', '50% 50%', '50% 24%'],
    ),
    responsibilities: [
      '维护项目周表和问题清单，点对点跟进项目进度',
      '组织月度交流会和选题咨询，帮助团队梳理方向',
      '服务项目立项、结题、评优和省赛衔接',
      '培育种子项目，把阶段问题转化为可执行的下一步',
    ],
    stats: [
      { value: 50, suffix: '项', label: '完成结题', note: '持续跟进项目材料与节点' },
      { value: 10, suffix: '项', label: '优秀项目', note: '在结题项目中形成示范成果' },
      { value: 4, suffix: '项', label: '进入省赛', note: '完成校内培育与赛事衔接' },
      { value: 2, suffix: '项', label: '进入省赛决赛', note: '继续接受针对性打磨' },
    ],
    workflow: [
      { title: '发现方向', description: '通过咨询会和交流活动梳理选题价值与现实问题。' },
      { title: '建立周表', description: '把目标拆成节点，记录负责人、进展和待解决事项。' },
      { title: '点对点跟进', description: '围绕材料、技术和表达问题持续沟通，推动阶段交付。' },
      { title: '结题与评优', description: '核对成果与材料，支持结题、评优和赛事推荐。' },
      { title: '继续培育', description: '为潜力项目连接咨询、路演和更高层级赛事资源。' },
    ],
    gains: ['项目管理与问题拆解能力', '与不同专业团队沟通的经验', '从立项到结题的完整科创视角'],
    starterAction: '跟着一张项目周表，更新一次真实进度。',
    related: ['competition', 'science'],
  },
  {
    id: 'competition',
    name: '竞赛部',
    summary: '连接团队、材料、专家和赛场，把赛事准备中的每个关键环节组织起来。',
    mission: '让每一次参赛准备都有清晰标准和可靠支撑。',
    accent: '#ff6f61',
    hero: hero('competition', '竞赛部在赛事培训现场为参赛团队讲解备赛要求', '50% 45%'),
    gallery: gallery('competition', [
      '竞赛部组织路演训练并观察团队现场表现',
      '竞赛培训结束后成员与参赛同学合影',
      '竞赛部面向团队开展材料与赛事要求培训',
    ]),
    responsibilities: [
      '收集报名与参赛材料，完成赛道分类和专家送审',
      '审核省赛材料与真实性信息，跟进反馈整改',
      '组织赛事训练营、多轮指导和专家培训',
      '完成材料归档、现场支持和突发情况协调',
    ],
    stats: [],
    workflow: [
      { title: '赛前收集', description: '确认团队、赛道、材料和时间节点，建立清晰清单。' },
      { title: '分类送审', description: '按赛道整理材料并对接专家，保证信息准确可查。' },
      { title: '反馈整改', description: '汇总审核意见，逐项提醒团队修改并再次核对。' },
      { title: '训练支持', description: '组织路演、答辩和专家培训，帮助团队理解赛事要求。' },
      { title: '现场保障', description: '处理人员、材料和时段变化，及时上报异常情况。' },
    ],
    gains: ['赛事规则与材料规范意识', '高压节点下的协调和应变能力', '路演评审与现场执行经验'],
    starterAction: '按一份赛事通知，整理报名材料和时间节点。',
    related: ['training', 'project'],
  },
  {
    id: 'training',
    name: '赛训部',
    summary: '把训练、带队和现场保障连成一条线，让参赛团队以更好的状态走上赛场。',
    mission: '用训练提升竞争力，用保障守住关键时刻。',
    accent: '#f2c14e',
    hero: hero('training', '赛训部服务的获奖团队在省级赛事现场合影', '50% 35%'),
    gallery: gallery('training', [
      '赛训部在科技文化节现场承担活动服务',
      '师生在科技文化节现场交流科创作品',
      '赛训部组织科创引领与项目能力交流活动',
    ]),
    responsibilities: [
      '组织赛事训练、选题咨询和阶段性模拟',
      '负责带队、物资、人员、时段与异常上报',
      '服务科技文化节和“大挑”选题咨询会',
      '把团队需求与导师、场地和赛事安排及时衔接',
    ],
    stats: [
      { value: 3, suffix: '个', label: '省级特等奖', note: '团队在省级赛事中取得成绩' },
      { value: 1, suffix: '个', label: '省级一等奖', note: '训练与现场保障共同推进' },
      { value: 7, suffix: '个', label: '省级二等奖', note: '覆盖多支参赛团队' },
      { value: 8, suffix: '个', label: '省级三等奖', note: '持续扩大赛事参与成果' },
    ],
    workflow: [
      { title: '了解队伍', description: '确认项目阶段、成员分工与当前训练需求。' },
      { title: '制定训练', description: '安排选题咨询、模拟路演和针对性打磨。' },
      { title: '赛前核对', description: '核实人员、物资、时段和现场注意事项。' },
      { title: '带队保障', description: '在赛场处理变化、反馈信息并保证团队衔接。' },
      { title: '赛后总结', description: '整理成绩与问题，为下一阶段训练积累经验。' },
    ],
    gains: ['赛事训练组织能力', '带队与现场保障经验', '与项目团队和导师协同的能力'],
    starterAction: '旁听一次模拟路演，记下三个可以继续打磨的问题。',
    related: ['competition', 'language'],
  },
  {
    id: 'science',
    name: '科素部',
    summary: '围绕科研写作、科技制图、路演答辩和 AI 工具，帮助同学补齐科创基本功。',
    mission: '把科研方法讲清楚，把科创能力练扎实。',
    accent: '#7cc576',
    hero: hero('science', '科素部面向同学开展科创能力分享', '50% 38%'),
    gallery: gallery(
      'science',
      [
        '科素部面向同学开展科研与技能培训',
        '科素部在课堂中讲解科技写作与表达方法',
        '科素部发布技能社群与课程学习信息',
      ],
      ['50% 42%', '50% 50%', '50% 22%'],
    ),
    responsibilities: [
      '组织文献综述、科技制图和科技论文比赛',
      '开展学术写作、PPT 制作、路演答辩和 AI 工具培训',
      '运营商业计划书、PPT、AI 和路演答辩技能社群',
      '连接科研学习、项目孵化与创新创业能力培养',
    ],
    stats: [
      { value: 3, suffix: '类', label: '科创能力赛事', note: '覆盖文献、制图与论文写作' },
      { value: 4, suffix: '类', label: '技能学习社群', note: '持续分享工具、方法与训练资源' },
    ],
    workflow: [
      { title: '识别能力缺口', description: '从写作、制图、展示或工具使用中定位学习需要。' },
      { title: '设计训练内容', description: '把复杂方法拆成可理解、可操作的课程与任务。' },
      { title: '组织比赛实践', description: '通过真实作品和赛事要求检验学习成果。' },
      { title: '社群持续答疑', description: '沉淀资料、案例和常见问题，帮助同学继续练习。' },
    ],
    gains: ['科研写作与信息检索能力', 'PPT、制图和 AI 工具使用能力', '把知识转化为培训内容的经验'],
    starterAction: '把一页复杂资料整理成一份清楚的图文笔记。',
    related: ['project', 'publicity'],
  },
  {
    id: 'publicity',
    name: '宣传部',
    summary: '用推文、视觉、影像和活动记录，让科创故事被看见、被理解、被记住。',
    mission: '记录真实科创现场，做有内容也有审美的表达。',
    accent: '#ff8f70',
    hero: hero('publicity', '宣传部成员参与校际科创交流并完成现场记录', '50% 46%'),
    gallery: gallery('publicity', [
      '宣传部在课堂活动中拍摄并整理现场内容',
      '宣传部参与校际交流活动并完成集体合影',
      '宣传部记录中心团队活动与成员风采',
    ]),
    responsibilities: [
      '策划和制作公众号推文、活动海报与校内展板',
      '运营科创 idol、赛事情报站和赛事交流营等栏目',
      '拍摄活动纪实，整理图片、视频与文字素材',
      '参与外部媒体、跨校交流和科创 IP 建设',
    ],
    stats: [
      { value: 2, suffix: '期', label: '科创 idol', note: '平均阅读量 1034.5' },
      { value: 3, suffix: '期', label: '赛事情报站', note: '平均阅读量 476.75' },
      { value: 9, suffix: '期', label: '赛事交流营', note: '平均阅读量 274.3' },
    ],
    workflow: [
      { title: '理解任务', description: '明确活动目的、受众、时间和发布载体。' },
      { title: '建立框架', description: '确定标题、文字结构、视觉方向与素材清单。' },
      { title: '现场采集', description: '拍摄关键人物、过程和成果，及时补齐信息。' },
      { title: '编辑呈现', description: '完成写作、设计、排版和多轮校对。' },
      { title: '发布复盘', description: '检查传播效果并沉淀模板、素材和栏目经验。' },
    ],
    gains: ['新闻写作与公众号排版能力', '海报、摄影和视觉表达经验', '从现场素材到完整作品的策划能力'],
    starterAction: '用三张照片和三句话，记录一次正在发生的活动。',
    related: ['language', 'office'],
  },
  {
    id: 'language',
    name: '语培部',
    summary: '通过路演、答辩、表达和仪态训练，帮助团队把项目讲清楚、讲准确、讲出感染力。',
    mission: '让有价值的项目，被更清晰、更自信地表达出来。',
    accent: '#b78cff',
    hero: hero('language', '语培部成员在表达训练与人文活动后合影', '50% 42%'),
    gallery: gallery('language', [
      '语培部成员开展拼豆等人文创意活动',
      '语培部完成主题活动并与参与同学合影',
      '语培部在课堂中组织表达训练和团队交流',
    ]),
    responsibilities: [
      '开展路演、答辩、语言表达和仪态训练',
      '针对逻辑断层与表达怯场进行晚间打磨',
      '组织模拟演练，提供话术模板和限时答辩技巧',
      '联动校内外导师与专业主持人提供指导',
      '通过迎新、手工和文创活动增强部门氛围',
    ],
    stats: [
      { value: 4, suffix: '类', label: '核心表达训练', note: '路演、答辩、语言与仪态' },
      { value: 3, suffix: '类', label: '模拟支持', note: '话术、限时训练与现场演练' },
    ],
    workflow: [
      { title: '理解项目', description: '先看懂项目逻辑、核心成果和答辩要求。' },
      { title: '梳理话术', description: '把专业内容整理成结构清晰、重点明确的表达。' },
      { title: '模拟演练', description: '在限时环境中练习路演、问答和舞台仪态。' },
      { title: '针对性打磨', description: '围绕怯场、逻辑断层和现场反应逐项调整。' },
      { title: '形成模板', description: '沉淀可复用的话术和训练方法，支持后续团队。' },
    ],
    gains: ['路演答辩与公众表达能力', '把专业内容转化为清晰话术的能力', '舞台应变与团队辅导经验'],
    starterAction: '选一个熟悉的话题，试着讲成一分钟的清楚版本。',
    related: ['publicity', 'training'],
  },
]
