import type { JourneySceneDefinition } from './types'

export const hubDestinations = [
  {
    sceneId: 'observation',
    title: '探索镜',
    invitation: '移动一束光，看看暗处藏着什么变化。',
    duration: '15 秒',
    objectType: 'lens',
    dialogue: '这边有一点不寻常，要不要照亮看看？',
  },
  {
    sceneId: 'clues',
    title: '磁吸星图',
    invitation: '把两块信息送进轨道，看看它们会怎样连接。',
    duration: '20 秒',
    objectType: 'orbit',
    dialogue: '零散信息也能组成路线，先挑两块试试。',
  },
  {
    sceneId: 'dialogue',
    title: '信号接力',
    invitation: '找一个人问清楚，让模糊的问题继续向前。',
    duration: '20 秒',
    objectType: 'relay',
    dialogue: '不知道没关系，找到能补上信息的人就行。',
  },
  {
    sceneId: 'map',
    title: '能量路线',
    invitation: '接上时间、伙伴和第一步，让小任务启动。',
    duration: '20 秒',
    objectType: 'route',
    dialogue: '路线不用很长，只要第一步能够落地。',
  },
  {
    sceneId: 'expression',
    title: '广播选择',
    invitation: '选择一种表达方式，把发现发送给别人。',
    duration: '20 秒',
    objectType: 'broadcast',
    dialogue: '发现被讲清楚，才会进入下一次协作。',
  },
] as const

export const journeyScenes: JourneySceneDefinition[] = [
  {
    id: 'observation',
    eyebrow: 'NIGHT STOP 01 / 微光现场',
    title: '先别急着找答案',
    prompt: '这片校园夜色里，哪两处让你想多看一眼？',
    instruction: '点亮两处异常，看看一件小事从哪里开始。',
    choices: [
      { id: 'detail', label: '反复修改的表格', caption: '同一格内容被改了三次。' },
      { id: 'people', label: '仍在讨论的同学', caption: '他们似乎还没找到共同说法。' },
      { id: 'place', label: '亮着灯的空教室', caption: '黑板上留下了一条未完成的路线。' },
    ],
    completionCaption: '你已经开始观察。很多研究，就从多看一眼开始。',
    mascotPose: 'focus',
  },
  {
    id: 'clues',
    eyebrow: 'NIGHT STOP 02 / 信号筛选',
    title: '把有用的碎片留下',
    prompt: '如果只能带走两条线索，你会选哪两条？',
    instruction: '选择两张线索卡，也可以跳过这一站。',
    choices: [
      { id: 'beginner-note', label: '新手的疑问', caption: '“我没有经验，也能参与吗？”' },
      { id: 'project-record', label: '项目进度记录', caption: '几个节点之间还缺一次确认。' },
      { id: 'event-image', label: '现场照片', caption: '照片里藏着事情发生的顺序。' },
      { id: 'schedule-gap', label: '空出的时间段', caption: '周末下午，刚好够做一次小尝试。' },
    ],
    completionCaption: '筛选不是猜对答案，而是决定下一步值得了解什么。',
    mascotPose: 'research',
  },
  {
    id: 'dialogue',
    eyebrow: 'NIGHT STOP 03 / 十秒对话',
    title: '找一个人问清楚',
    prompt: '谁能帮你最快补上缺失的信息？',
    instruction: '选择一位角色，听听他从哪里看这件事。',
    choices: [
      { id: 'newcomer', label: '刚入门的同学', caption: '他说出第一次参与时最担心的事。' },
      { id: 'participant', label: '项目参与者', caption: '他知道团队现在卡在哪一步。' },
      { id: 'mentor', label: '指导老师', caption: '他提醒你先把问题范围说清楚。' },
    ],
    completionCaption: '你不需要一个人知道全部，问对人也是推进问题的方法。',
    mascotPose: 'focus',
  },
  {
    id: 'map',
    eyebrow: 'NIGHT STOP 04 / 行动组装',
    title: '把想法接上现实',
    prompt: '为这次小行动选好时间、伙伴和第一步。',
    instruction: '每组选择一项，路线会在地图上逐段亮起。',
    choices: [
      { id: 'short', label: '课后半小时', caption: '从短时间、低压力开始。', group: 'time' },
      { id: 'weekend', label: '周末下午', caption: '留出一次完整的小尝试。', group: 'time' },
      { id: 'flexible', label: '找到空档就做', caption: '把任务拆成随时能推进的小步。', group: 'time' },
      { id: 'peer', label: '找一位同伴', caption: '两个人先把想法说清楚。', group: 'partner' },
      { id: 'team', label: '加入一个小组', caption: '把不同视角放到同一张图上。', group: 'partner' },
      { id: 'solo', label: '先独立整理', caption: '先做一份能交流的初稿。', group: 'partner' },
      { id: 'try-first', label: '先做一次', caption: '用小实验换来真实反馈。', group: 'approach' },
      { id: 'research-first', label: '先查清资料', caption: '从可靠信息里缩小问题。', group: 'approach' },
      { id: 'ask-first', label: '先请教别人', caption: '让有经验的人帮你避开弯路。', group: 'approach' },
    ],
    completionCaption: '路线不必宏大。能开始、有人一起、知道第一步，就足够出发。',
    mascotPose: 'launch',
  },
  {
    id: 'expression',
    eyebrow: 'NIGHT STOP 05 / 结果显影',
    title: '让发现被别人看见',
    prompt: '你想用哪种方式留下这次发现？',
    instruction: '选择一种顺手的表达，完成本次夜航。',
    choices: [
      { id: 'map', label: '一张路线图', caption: '把节点和关系画清楚。' },
      { id: 'poster', label: '一张海报', caption: '让重点在几秒内被看见。' },
      { id: 'video', label: '一段短片', caption: '用画面还原过程和变化。' },
      { id: 'sharing', label: '一次现场分享', caption: '把发现讲给真实的人听。' },
    ],
    completionCaption: '表达不是最后的装饰，它会让一次探索真正进入协作。',
    mascotPose: 'cheer',
  },
]
