import type { CosmicWorldId, ExplorerPose, SceneVisual } from './types'

export const sceneVisuals: Record<CosmicWorldId, SceneVisual> = {
  intro: {
    desktopSrc: '/media/night-voyage/intro-earth.webp',
    mobileSrc: '/media/night-voyage/intro-earth.webp',
    desktopVideoSrc: '/media/night-voyage/intro-earth-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/intro-earth-mobile.mp4',
    posterSrc: '/media/night-voyage/intro-earth.webp',
    alt: '真实地球从深空中缓慢升起，城市灯光沿大陆边缘闪烁',
    focalPoint: '62% 58%',
    accent: '#6ce8ff',
  },
  hub: {
    desktopSrc: '/media/night-voyage/hub-starlight-valley.webp',
    mobileSrc: '/media/night-voyage/hub-starlight-valley.webp',
    desktopVideoSrc: '/media/night-voyage/hub-starlight-valley-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/hub-starlight-valley-mobile.mp4',
    posterSrc: '/media/night-voyage/hub-starlight-valley.webp',
    alt: '探索者沿着发光峡谷驶向星海，五个目的地等待选择',
    focalPoint: '50% 52%',
    accent: '#4be4f4',
  },
  observation: {
    desktopSrc: '/media/night-voyage/observation-forest.webp',
    mobileSrc: '/media/night-voyage/observation-forest.webp',
    desktopVideoSrc: '/media/night-voyage/observation-forest-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/observation-forest-mobile.mp4',
    posterSrc: '/media/night-voyage/observation-forest.webp',
    alt: '幽暗森林里一束光照亮植物与遗迹，等待进一步观察',
    focalPoint: '58% 50%',
    accent: '#60d8ff',
  },
  clues: {
    desktopSrc: '/media/night-voyage/clues-green-planet.webp',
    mobileSrc: '/media/night-voyage/clues-green-planet.webp',
    desktopVideoSrc: '/media/night-voyage/clues-green-planet-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/clues-green-planet-mobile.mp4',
    posterSrc: '/media/night-voyage/clues-green-planet.webp',
    alt: '绿色行星在星云中缓慢转动，信息碎片沿轨道聚合',
    focalPoint: '62% 54%',
    accent: '#5bf3df',
  },
  dialogue: {
    desktopSrc: '/media/night-voyage/dialogue-cosmic-mind.webp',
    mobileSrc: '/media/night-voyage/dialogue-cosmic-mind.webp',
    desktopVideoSrc: '/media/night-voyage/dialogue-cosmic-mind-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/dialogue-cosmic-mind-mobile.mp4',
    posterSrc: '/media/night-voyage/dialogue-cosmic-mind.webp',
    alt: '星光从人物思绪中扩散，等待一段新的对话接入',
    focalPoint: '52% 52%',
    accent: '#80a8ff',
  },
  map: {
    desktopSrc: '/media/night-voyage/map-black-hole.webp',
    mobileSrc: '/media/night-voyage/map-black-hole.webp',
    desktopVideoSrc: '/media/night-voyage/map-black-hole-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/map-black-hole-mobile.mp4',
    posterSrc: '/media/night-voyage/map-black-hole.webp',
    alt: '黑洞边缘的光流形成航路，三个行动节点等待连接',
    focalPoint: '50% 24%',
    accent: '#6bd8ff',
  },
  expression: {
    desktopSrc: '/media/night-voyage/expression-triptych.webp',
    mobileSrc: '/media/night-voyage/expression-triptych.webp',
    desktopVideoSrc: '/media/night-voyage/expression-triptych-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/expression-triptych-mobile.mp4',
    posterSrc: '/media/night-voyage/expression-triptych.webp',
    alt: '晨光越过群山，三块联动画面等待发送新的表达信号',
    focalPoint: '50% 50%',
    accent: '#61eddf',
  },
  result: {
    desktopSrc: '/media/night-voyage/result-collaboration.webp',
    mobileSrc: '/media/night-voyage/result-collaboration.webp',
    desktopVideoSrc: '/media/night-voyage/result-collaboration-desktop.mp4',
    mobileVideoSrc: '/media/night-voyage/result-collaboration-mobile.mp4',
    posterSrc: '/media/night-voyage/result-collaboration.webp',
    alt: '伙伴们在星空下围绕发光屏幕协作，行动正在真实发生',
    focalPoint: '50% 56%',
    accent: '#7be7ff',
  },
  atlas: {
    desktopSrc: '/environments/atlas.webp',
    mobileSrc: '/environments/atlas-mobile.webp',
    alt: '七个部门化作不同轨道上的星体，组成完整科创星系',
    focalPoint: '68% 48%',
    accent: '#67e9ef',
  },
}

export const explorerPoseSources: Record<ExplorerPose, string> = {
  wake: '/explorer/wake.webp',
  idle: '/explorer/idle.webp',
  walk: '/explorer/walk.webp',
  observe: '/explorer/observe.webp',
  touch: '/explorer/touch.webp',
  record: '/explorer/record.webp',
  communicate: '/explorer/communicate.webp',
  enter: '/explorer/enter.webp',
}
